name: "p7zip"

on:
  schedule:
    - cron: '0 0 * * *'

permissions: write-all

jobs:
  p7zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: p7zip
      shell: bash
      run: |
        bash --noprofile --norc -e -o pipefail .github/workflows/git-config.sh
        p7zip_version=$(curl -sSL "https://www.7-zip.org/" | tr '"' '\n' | tr "'" '\n' | grep -E '^a\/7z[0-9]+-x64\.exe$' | head -1)
        echo "$p7zip_version"
        p7zip_version=${p7zip_version:4:-8}
        echo "$p7zip_version"
        sed -i "0,/\"p7zip-version\": \".*\"/s//\"p7zip-version\": \"$p7zip_version\"/" downloadlist.json
        git add downloadlist.json
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Update 7z to $p7zip_version" || true
        echo "p7zip_version=$p7zip_version" >> $GITHUB_ENV
    - id: cpr
      uses: peter-evans/create-pull-request@v8.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update README
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: "Update 7z to ${{ env.p7zip_version }}"
        body: |
          Update 7-Zip to the latest version found on https://www.7-zip.org/
          
          Changelog: https://www.7-zip.org/history.txt
        labels: automerge
        branch: actions/p7zip
        base: master
    - name: get repository name
      if: ${{ steps.cpr.outputs.pull-request-number }}
      shell: bash
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - name: automerge
      if: ${{ steps.cpr.outputs.pull-request-number }}
      uses: actions/github-script@v8.0.0
      with:
        script: |
          github.rest.pulls.merge({
            owner: '${{ github.repository_owner }}',
            repo: '${{ env.REPOSITORY_NAME }}',
            pull_number: '${{ steps.cpr.outputs.pull-request-number }}',
            sha: '${{ steps.cpr.outputs.pull-request-head-sha }}',
            merge_method: 'merge'
          })
