name: PortableGit

on:
  schedule:
    - cron: '0 0 * * *'

permissions: write-all

jobs:
  portable-git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.1
    - name: PortableGit
      shell: bash
      run: |
        bash --noprofile --norc -e -o pipefail .github/workflows/git-config.sh
        portable_git_version=$(curl -sS "https://api.github.com/repos/git-for-windows/git/releases/latest" | python -c "import sys, json; print(json.load(sys.stdin)['tag_name'])")
        echo "$portable_git_version"
        portable_git_version=${portable_git_version:1}
        echo "$portable_git_version"
        sed -i "0,/\"portable-git-version\": \".*\"/s//\"portable-git-version\": \"$portable_git_version\"/" downloadlist.json
        git add downloadlist.json
        git -c user.name="GitHub" -c user.email="noreply@github.com" commit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m"Update PortableGit to $portable_git_version" || true
        echo "portable_git_version=$portable_git_version" >> $GITHUB_ENV
    - id: cpr
      uses: peter-evans/create-pull-request@v8.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update README
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        title: "Update PortableGit to ${{ env.portable_git_version }}"
        body: |
          Update PortableGit to the latest version found on https://github.com/git-for-windows/git/releases
          
          Changes: https://github.com/git-for-windows/git/releases/latest
        labels: automerge
        branch: actions/portable-git
        base: master
    - name: get repository name
      if: ${{ steps.cpr.outputs.pull-request-number }}
      shell: bash
      run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - name: automerge
      if: ${{ steps.cpr.outputs.pull-request-number }}
      uses: actions/github-script@v8.0.0
      with:
        script: |
          github.rest.pulls.merge({
            owner: '${{ github.repository_owner }}',
            repo: '${{ env.REPOSITORY_NAME }}',
            pull_number: '${{ steps.cpr.outputs.pull-request-number }}',
            sha: '${{ steps.cpr.outputs.pull-request-head-sha }}',
            merge_method: 'merge'
          })
